name: xyalign_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bbmap=36.32=0
  - bcftools=1.5=3
  - bedtools=2.26.0=0
  - bwa=0.7.15=0
  - curl=7.45.0=2
  - cyvcf2=0.7.2=py27_0
  - expat=2.1.0=0
  - htslib=1.5=0
  - java-jdk=8.0.92=1
  - libxml2=2.9.3=0
  - platypus-variant=0.8.1.1=htslib1.5_0
  - pybedtools=0.7.10=py27_1
  - pysam=0.12.0.1=htslib1.5_0
  - python-dateutil=2.3=py27_0
  - sambamba=0.6.6=0
  - samtools=1.5=0
  - bzip2=1.0.6=1
  - cairo=1.14.6=0
  - cycler=0.10.0=py27_0
  - dbus=1.10.10=0
  - fontconfig=2.12.1=0
  - freetype=2.5.5=1
  - functools32=3.2.3.2=py27_0
  - glib=2.50.2=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - icu=54.1=0
  - jpeg=8d=2
  - libffi=3.2.1=1
  - libgcc=5.2.0=0
  - libgfortran=3.0.0=1
  - libiconv=1.14=0
  - libpng=1.6.27=0
  - libxcb=1.12=1
  - matplotlib=2.0.2=np113py27_0
  - mkl=2017.0.3=0
  - numpy=1.13.1=py27_0
  - openssl=1.0.2j=0
  - pandas=0.20.2=np113py27_0
  - pcre=8.39=1
  - pip=9.0.1=py27_1
  - pixman=0.34.0=0
  - pycairo=1.10.0=py27_0
  - pyparsing=2.1.4=py27_0
  - pyqt=5.6.0=py27_1
  - python=2.7.13=0
  - pytz=2016.10=py27_0
  - qt=5.6.2=2
  - readline=6.2=2
  - scipy=0.19.1=np113py27_0
  - seaborn=0.7.1=py27_0
  - setuptools=27.2.0=py27_0
  - sip=4.18=py27_0
  - six=1.10.0=py27_0
  - sqlite=3.13.0=0
  - subprocess32=3.2.7=py27_0
  - tk=8.5.18=0
  - wheel=0.29.0=py27_0
  - xz=5.2.2=1
  - zlib=1.2.8=3
